language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master
env:
  - apiKey=$apiKey,
  - authDomain=$authDomain,
  - databaseURL=$databaseURL,
  - projectId=$projectId,
  - storageBucket=$storageBucket,
  - messagingSenderId=$messagingSenderId

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: support@lazy.menu
    on_success: support@lazy.menu
